### PR TITLE
Code pipeline

### PR DESCRIPTION
**Pull request by tylersouthwick**

### CODE REVIEW

**Comment by tj-corrigan** [comment]
Working through comparing this to the CF docs. I'll finish it up tomorrow.

**Comment by tylersouthwick** [comment]
ping

**Comment by bkrodgers** [comment]
@tj-corrigan let me know if you've already looked at this or still plan to.  Otherwise I can take it.

**Comment by tylersouthwick** [comment]
have you had a chance to look at it yet?

**Comment by bkrodgers** [comment]
I'll take a look at this one.  Sorry for the delay!

**Comment by bkrodgers** [comment]
This looks good.  Sorry you had to wait so long.

**Pull request merged**
