### PR TITLE
Cross compile

### PR DESCRIPTION
**Pull request by tylersouthwick**
This gets everything to cross compile between 2.11 and 2.10. There are a few changes needed:
- Some type inferences (multiple levels) don't work in 2.10, so I manually put them in
- Yaml.scala caused 2.10 compiler to fail with a NullPointerException, so it is currently not available in 2.10
- Due to the case class parameter count limitations in 2.10, I moved RDS and RedShift support to only 2.11

We might be able to accomplish it in other ways - this is a first stab at solving the problem.

Addresses #86

### CODE REVIEW

**Comment by bpholt** [comment]
This is great. I was going to play around with manually implementing the case class functionality due to the parameter count limitation in 2.10 (I'm not sure whether that's really feasible or not, but I thought it would be worth a shot), but you've made a huge amount of progress.

**Comment by tj-corrigan** [comment]
@tylersouthwick: While this one isn't compiling yet I noticed you made some changes recently. Is this something you still want to get in?

**Comment by tylersouthwick** [comment]
I merged master into it, but not sure if there is value in pursuing this.
Scala 2.12 will make this more difficult.

**Comment by bpholt** [comment]
FWIW, I was the original requestor, and I agree that this isn't super valuable anymore. We wanted 2.10 support originally to include this library in an sbt plugin, but we've worked around that successfully already. Thanks for your time and effort on it, though!

**Comment by bkrodgers** [comment]
FWIW, we do have 2.12 support (and still support 2.11) now!

**Comment by tj-corrigan** [comment]
Thanks, closing this then.

**Pull request closed without merging**
