### PR TITLE
Add Kinesis support

### PR DESCRIPTION
**Pull request by carsonfarrell**
I noticed that Kinesis support was not available, and needed it for my project

### CODE REVIEW

**Comment by tj-corrigan** [comment]
don't worry about the decrease in test coverage, I'll review this shortly.

**Comment by carsonfarrell** [comment]
Cool, thanks for the fast turnaround time on replying.

Was getting questions from coworkers about whether your library was
actively supported or not, this gives me backing to continue using it.

**Comment by tj-corrigan** [comment]
LGTM, thanks for the contribution! I'll try and get a few of these other lingering ones in and cut a new release for you later today.

**Comment by carsonfarrell** [comment]
Awesome, thanks!

**Pull request merged**
