### PR TITLE
Add Cloudfront

### PR DESCRIPTION
**Pull request by tylersouthwick**

### CODE REVIEW

**Comment by bkrodgers** [comment]
Sorry for the delay on looking at this one.  Have you run some tests against AWS on this?  We haven't done much with CloudFront here, so I'd have to school up a bit to test that myself.

**Comment by tylersouthwick** [comment]
I tested it with the use cases I had which were pretty simple and straight
forward.

**Comment by bkrodgers** [comment]
I'm wondering if some of the values on `DistributionConfig` and its related types should be `Token[String]` instead of `String`, so they can be references to other resources or parameters.  For example, you might want to pass a `ResourceRef` for the `WebACLId` parameter, since you could define that as a `AWS::WAF::WebACL` (though we haven't modeled WAF yet).  There may be others that should be as well.

Thoughts?

**Comment by tj-corrigan** [comment]
@tylersouthwick If you fix up the conflicts I'll go ahead and merge this one too.

**Comment by tylersouthwick** [comment]
rebased off of master. should be good to go.

**Pull request merged**
