### PR TITLE
Adding PrivateIpAddress attribute for Instance.

### LINKED ISSUE #49: Support PrivateIpAddress for Instance
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-privateipaddress

### PR DESCRIPTION
**Pull request by guoshimin**
Fixes #49.

### CODE REVIEW

**Comment by tj-corrigan** [comment]
I'm thinking that even though the IP address is a `String` we should add some type safety to the parameter similar to how [`CIDRBlock`](https://github.com/MonsantoCo/cloudformation-template-generator/blob/master/src/main/scala/com/monsanto/arch/cloudformation/model/resource/EC2.scala#L220-L233]) was implemented.

**Comment by guoshimin** [comment]
Yeah, will use CidrBlock instead.

**Comment by tj-corrigan** [comment]
We just merged in an `IPAddress` type that can be used ( see https://github.com/MonsantoCo/cloudformation-template-generator/blob/master/src/main/scala/com/monsanto/arch/cloudformation/model/resource/EC2.scala#L235-L248).

**Comment by guoshimin** [comment]
Done. PTAL.

**Pull request merged**
