### PR TITLE
Nat gateway support (custom CF type)

### PR DESCRIPTION
**Pull request by bkrodgers**
Change also includes improvements to the EIP model and adds the ability to specify a name for a load balancer.

### CODE REVIEW

**Comment by tj-corrigan** [comment]
To keep the history clean lets squash this guy

**Comment by tylersouthwick** [comment]
instead of using the cli in a bash script, it could all be scripted using the template library since lambdas are supported. That way, it won't overwrite any functions currently in the account

**Comment by bkrodgers** [comment]
@tylersouthwick: Thanks Tyler!  I did consider that when I put this together.  There are two ways you could set up the Lambda function with CF.  They both have downsides.

One would be to just provide a CF template for a one time load, instead of this bash script.  The downside here is that the function gets created with a random ARN.  So the template would need to be provided the ARN for the account and region you're running the template in.  The bash script will upload it to a constant name, and I've provided a default that templates can reference to construct the ARN from that constant, the account ID, and the region. 

The other approach would be to include creating the function in every template itself.  This solves the ARN problem, since you can reference it within the template.  The problem now is that you're uploading the function for every stack you stamp out on that template.  There's a 1.5GB limit on Lambda code per account, and the zip file for this function is 665KB (Amazon doesn't provide a current version of their SDK in the Lambda environment, so it must be bundled).  Granted, there's lots of room to upload 665KB many times in 1.5GB, but if you're using Lambda for other things, and if you stand up lots of VPCs in an AWS account, it may be a concern.  I know it would be for us right now, but it might not be a big deal for people with a low VPC/Account ratio and those who don't use Lambda heavily.

So neither are showstoppers, but the script based approach seemed to solve both.  What do you think?  I could certainly provide a CF based option as well, but I think at least in my case I'd probably stick with the script.  I could also just mention in the document that CF is an alternative option but not provide it.

**Comment by bkrodgers** [comment]
@tj-corrigan Thanks -- i'd squashed it earlier and meant to resquash before submitting, but forgot.  Done now.

**Comment by tj-corrigan** [comment]
We also wouldn't have an automated way of cleaning up all the lambda functions. 

I'm OK with this approach for now hoping that CloudFormation has a native solution for this in the not too distant future.

**Comment by tylersouthwick** [comment]
@bkrodgers interesting constraints. I wasn't too familiar with the size limitations. Neither option is optimal... but the script is as good as any right now

**Pull request merged**
