### PR TITLE
Update AWS::Events::Rule

### PR DESCRIPTION
**Pull request by seanmcl**
Note that this will break callers of the existing rule.  I don't know a way around this while still allowing users to use EventPatterns.

### CODE REVIEW

**Comment by bkrodgers** [comment]
Couldn't you just add an `apply` method of:

```
 apply(name: String,
           ScheduleExpression: Token[String],
           Targets: Seq[Option[RuleTarget]])
```

And if we want to cover people who might have used a condition, also add:
```
 apply(name: String,
           ScheduleExpression: Token[String],
           Targets: Seq[Option[RuleTarget]]),
           Condition: Option[ConditionRef]
```

Those methods would need to flip the weird `Seq[Option[RuleTarget]])` into the new format...not sure why it was ever defined that way.  Good call on fixing it.

**Comment by seanmcl** [comment]
Yes, I could definitely do that.  I'll mark it as deprecated so one day soonish we can remove it :)

**Comment by seanmcl** [comment]
@bkrogers Done.

**Comment by tj-corrigan** [comment]
We should probably also enforce the condition that `EventPattern` and/or  `ScheduleExpression` be specified.

**Pull request merged**
