### PR TITLE
Make TracingConfig an enum

### PR DESCRIPTION
**Pull request by seanmcl**
Fixes serialization bug: #233

### CODE REVIEW

**Comment by bpholt** [comment]
FWIW, I ran into #233, and having checked out and built this PR locally, it seems to have solved the problem for me locally. Looking forward to it being merged and published so I can use the fix in production. 😃

**Comment by bkrodgers** [comment]
Sorry for the delay -- I was out most of December!  I take it this isn't a breaking change...since the functionality sounds like it was already broken.  :)

**Comment by seanmcl** [comment]
Right.

**Comment by jacobm** [comment]
What is the expected timeframe until this is released? I just ran into the same issue.

**Comment by seanmcl** [comment]
Anyone on Monsanto team mind if I throw a fork of this repo up on maven central?  I don't want to step on anyone, but it would make our workflow nicer if we could pick up more regular updates.

**Comment by bkrodgers** [comment]
Sorry I've fallen behind a bit.  Working on a release now.

**Pull request merged**
