### PR TITLE
Add VPN support

### PR DESCRIPTION
**Pull request by adamfokken**
I'm working on adding VPN support and one of the first things I'm trying to do is add VPNGateway Support to VPCGatewayAttachment. I've used AWS::EC2::Route as an example of how to apply "only one" parameter semantics to the resource. (Full disclosure I'm very new to Scala and its type system).

I think I've implemented correctly but the [Gateway builder trait](https://github.com/adamfokken/cloudformation-template-generator/blob/master/src/main/scala/com/monsanto/arch/cloudformation/model/simple/Builders.scala#L470) is complaining of inferred types.

Does the signature for VPCGatewayAttachment need to be modified?

### CODE REVIEW

**Comment by hibikir** [comment]
The types that VPCGatewayAttachment are overly complicated, and the implicit conversions are not written in such a way that they chain, so it's all very confusing, even with Scala experience, so don't despair: It's not on you

This makes the code compile, but the whole scheme should be changed to be easier.

```scala 
   trait Gateway {
     def withInternetGateway(implicit vpc: `AWS::EC2::VPC`) = {
     // internet gateway
     val gName = "InternetGateway"
     val gateway = `AWS::EC2::InternetGateway`(
       gName,
       Tags = AmazonTag.fromName(gName)
     )
     import Token._
     val attName = "GatewayToInternet"
     val attachment = `AWS::EC2::VPCGatewayAttachment`(
       name = attName,
       VpcId = vpc,
       InternetGatewayId = Some(fromResource(gateway))
     )

     (gateway, attachment)
     }
    }

**Comment by adamfokken** [comment]
Thanks! I appreciate the help.

**Comment by hibikir** [comment]
I also have a different approach to the multi parameter stuff, it has strengths and weaknesses. You can see it in my fork, straight of your fork. TJ is thinking about switching to it, but opinions are welcome.

https://github.com/hibikir/cloudformation-template-generator

**Comment by tj-corrigan** [comment]
I agree with @hibikir and think that it is cleaner solution that is probably worthy of switching to. Let's go ahead and PR those and use it as our template going forward.

**Comment by adamfokken** [comment]
It is certainly simpler for me to understand.

For those following along, like myself, the downside is that the declaration of the resources doesn't follow exactly the CF resource definitions?

Also, should [this](https://github.com/hibikir/cloudformation-template-generator/blob/vpnsupport/src/main/scala/com/monsanto/arch/cloudformation/model/resource/EC2.scala#L404) be a sealed trait?

**Comment by tj-corrigan** [comment]
I just merged it in but I'll go ahead and make it a sealed trait, good catch.

**Comment by tj-corrigan** [comment]
My mistake, that code isn't in master. That was just hibikir working off your branch. You are right though it should be sealed.

**Comment by adamfokken** [comment]
This should now be a PR that includes all necessary resources to implement a VPN setup.

**Pull request merged**
